version: 0.2

phases:
  install:
    commands:
      - echo "Installing system dependencies"
      - sudo apt update && sudo apt upgrade -y
      - sudo apt install git -y
      - echo "Installing CodeDeploy agent"
      - sudo apt-get install ruby -y
      - wget https://aws-codedeploy-us-east-1.s3.amazonaws.com/latest/install
      - chmod +x ./install
      - sudo ./install auto
      - sudo service codedeploy-agent start
      - sudo service codedeploy-agent status
      - curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - node -v
      - npm -v
      - echo "Cloning the GitHub repository"
      - git clone https://github.com/AbhishekAbhisharma/Nodes.git
      - cd Nodes/
      - echo "Installing Node.js dependencies"
      - npm install

  build:
    commands:
      - echo "Build started on `date`"
      
  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Installing PM2 and starting the application"
      - sudo npm install -g pm2
      - pm2 start index.js
      - pm2 save # Save the PM2 process list

artifacts:
  files:
    - '**/*' # Includes all files in the current directory
